mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.abc.itbbs.**.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true